language: objective-c
osx_image: xcode8.0
#xcode_project: _Pods.xcodeproj # path to your xcodeproj folder
#xcode_scheme: DGNotifyView
# cache: cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods -v 1.1.1
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/DGNotifyView.xcworkspace -scheme DGNotifyView-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
